[tool.black]
line-length = 88
target-version = ["py36", "py37", "py38"]
exclude = '''
/(
  \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.toml
  | \.sh
  | \.ini
  | Dockerfile
  | Jenkinfile
)/
'''

[tool.isort]
line_length = 79
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
